### ISSUE TITLE
Mcp become unrensponsive after some minutes

### ISSUE THREAD

**Issue by domcat11** [jpcornil-git/HA-mcp23017#11]
Hello.
First, thanks for your job. I've got a problem using the component. 
This is my configuration
- Rapberry PI3
- Home assistant installation: HASSIO, always update to last release
- custom component HA-mcp23017 installed via HACS
- all GPIO are set as input (binary sensor)
- no external pullup resistor on GPIO

I used a DIY breadboard to connected a MCP23017 IC to 3.3v power, 0V, bus SDA and SCK 

This is my yaml configuration
`binary_sensor:
  - platform: mcp23017
    i2c_address: 0x27
    invert_logic: true
    pull_mode: UP
    pins:
      0: finestra_ap_centrale
      1: finestra_ss_centrale
      2: finestra_ap_garage
      3: finestra_grata_ss_garage
      4: finestra_grata_ss_centrale
      5: finestra_grata_ss_sala
      6: volumetrico_vol_scala
      7: pfinestra_ap_sala
      8: pfinestra_grata_ss_sala
      9: pfinestra_grata_ap_sala
      10: volumetrico_vol_sala
      11: portone_ap_sala
      12: portone_ss_sala
      13: finestra_ap_sala
      14: mcp_free10
      15: mcp_free11
`
Initially, sensors works correctly as input: if I connect a GPIO to GND the relative sensor goes ON. if disconnected goes OFF.
All input are OK
But after some minutes (sometime after a couple of hours) it becomes unresponsive: sensors that were ON remain ON also if I disconnect from GND, and sensors that were OFF remain OFF also if connected to GND.

I've tried serveral MCP23017 chips, also two prepacked with connectors, 
I've tried also changing address, adding 4.7kOhm pull up resistor to SDA and SCK ...
Always same behavior: initially all works, after some minutes it freezes and become unresponsive

I tried also connecting 3 MCP to the same bus. they became all unrensponsive although at different time

In the log there is a "Remote I/O error". 
Full logs are attached (with one and three mcp )

please help.
Thanks

[home-assistant.log](https://g
[home-assistant_with 3 MCP.log](https://github.com/jpcornil-git/HA-mcp23017/files/9601951/home-assistant_with.3.MCP.log)
ithub.com/jpcornil-git/HA-mcp23017/files/9601915/home-assistant.log)

**Comment by jpcornil-git** [comment]
Hi @domcat11,

In your log, I see the following error for each device (0x27 at 12:44:08, 0x26: at 13:24:43 and 0x24 at 13:25:43)

`OSError: [Errno 121] Remote I/O error
`

This is related to a device not responding to a bus request for some reason (signal integrity issue, power loss, incorrect address, ...).

Do you have a schema of your setup (and pictures eventually) ?

Cheers,
jpc

**Comment by domcat11** [comment]
Hello
I think I found the problem. there waw also a BME280 (temperature unidity and pressure sensor) connected to the bus, far from RPI (8/9 meter). I just disconnect the wire to that sensor and now MCP are stable. 12 hours ago I've connected 4 MCPs to the bus with no problem so far.
By the way, my system is HAOS

I close the Issue.

Thanks for your interest in my problem.
Bye

**Comment by jpcornil-git** [comment]
Thanks for the feedback.

Given the distance, you may want to connect your BME280 to the I2C ifce of an ESP32 module loaded with ESPHome see https://esphome.io/components/sensor/bme280.html -> module will connect to your network using wifi and will automaticaly be detected by  HomeAssistant.

Cheers,
jpc

**Comment by jpcornil-git** [comment]
Note also that with the RPi i2c interface running at 400KHz and 1.8Kohms pull-up resistors, it will be difficult to use a generic cable longer than 2-3 meters (assuming 100pF/m) just because of the RC charging/time constant. If the above solution is not practical, you may want to try with cat6 cable (tick cable/low linear capacitance and shielded pairs); use three pairs [GND, SDA], [GND, SCL], and [GND, VCC] to improve signal integrity)

Cheers,
jpc

**Comment by domcat11** [comment]
Thanks for your suggestions
For my setup, CAT6E cable solution is very interesting because I've to place MCPs at about 4 meter far from RPI and I want a wired solution.
This suggestion is very useful, thanks again...

**Comment by domcat11** [comment]
Hi @jpcornil-git 
I think that connection problem is temporary (I think few seconds), In fact, in case of error, only the MCP in error become unresponsive (I think the relative thread exits because of the exception raising the code) and restarting HA solve the  unresponsivenes.
In your opinion, use a TRY/EXCEPT clause to avoid exception raising can be a good solution? 
Thanks again

**Comment by jpcornil-git** [comment]
Hi @domcat11,

This would be my guess as well, i.e. issue is intermittent not persistent.

The issue with a silent try-catch approach to try to hide a HW issue/weakness is that HA state and HW state may then be different/not synchronized anymore, e.g. HA think that heater is on but because of a communication issue it is effectively  off -> system is not reliable anymore (and as a consequence, you may think that stability is related to issue with HA/integration/automation script/...).

This is why I decided to expose such issue the hard way rather than try to mitigate it under the hood (hide/retry a number of time then give up/... none are great).
