### ISSUE TITLE
RuntimeWarning: coroutine 'ConfigEntries.async_remove' was never awaited

### ISSUE THREAD

**Issue by glcos** [jpcornil-git/HA-mcp23017#21]
```
2024-05-17 22:19:34.682 WARNING (MainThread) [py.warnings] /home/homeassistant/.homeassistant/custom_components/mcp23017/config_flow.py:61: RuntimeWarning: coroutine 'ConfigEntries.async_remove' was never awaited
  self.hass.config_entries.async_remove(config_entry.entry_id)
```

I'm getting this error in the log since quite a while, however the integration is working fine.
Maybe it can be fixed.
Thank you for the great integration!

**Comment by jpcornil-git** [comment]
Thanks for reporting,

Could you replace in your /home/homeassistant/.homeassistant/custom_components/mcp23017/config_flow.py (line 60-61) 

``` python
        if config_entry:
            self.hass.config_entries.async_remove(config_entry.entry_id)
```
with:
``` python
        if config_entry:
            await self.hass.config_entries.async_remove(config_entry.entry_id)
```
and report results ?

You are probably using a legacy yaml rather than a config flow configuration (yaml remove existing entries first and that is probably why you are seeing this while most don't). I can test myself such a configuration over the week-end as well if you are not confortable with the edits above.

Cheers,
jpc

**Comment by jpcornil-git** [comment]
Hi,
I tested a yaml configuration in a docker instance and after the second HA restart, I see the same warning in my log as well, i.e. the first start creates a config entry from yaml and the second one do the same after removing existing one from storage (but it fails because of this issue)
Applying the above patch fixes the issue.
Could you give it a try as well to make sure there are no side effects (I just commited adfc6ec -> you can just [reload you integration with beta enabled](https://hacs.xyz/docs/faq/beta/) and use that tag) and report results.

**Comment by glcos** [comment]
Hi,
I replaced config_flow.py with the updated one and the warning in the log is gone!
Thank you for the quick fix!

**Comment by jpcornil-git** [comment]
Thanks for the report !
I just tagged v1.2.2 with this commit -> you can now disable beta and update to latest
Cheers,
jpc
